### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by mandai2** [Nisto/musyx-extract#4]
I am using the -P option to replace the original .samp/.sdir files, however when my edited .dsp file plays it always loops. It could be a problem with my file but I was able to fix this by setting loop_start and loop_end to 0 in write_sdir.

**Comment by Nisto** [comment]
@mandai2 Late call, but do you still have that .dsp file, and can you confirm the header values at 0x10 (loop start; 4 bytes) and respectively 0x14 (loop end; 4 bytes)? If possible, post a screenshot of the values shown in a hex editor, or paste the raw hex bytes.

If there's an issue with the actual script, I'll try looking into it, but it does sound like it's the .dsp file that is at issue here. I'm also mostly trying to clear up any remnant issues in my personal projects on GitHub right now, since notifications have been notoriously bad here, in the past at least. Let me know ASAP as I hope to close these soon.
